name: Deploy fanTABulous

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run health check
        run: curl --fail https://localhost:5000/health || exit 1

      - name: Deploy to Render
        run: echo "Triggering Render deploy..." # Replace with actual deploy hook

services:
  - type: web
    name: fanTABulous-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
