"""add password reset token table

Revision ID: 53c9271c99f3
Revises: 9ee13a6cae30
Create Date: 2025-10-15 00:50:48.235592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53c9271c99f3'
down_revision: Union[str, Sequence[str], None] = '9ee13a6cae30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import uuid
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'password_reset_tokens' ,
        sa.Column('id' , sa.Integer() , primary_key=True) ,
        sa.Column('user_id' , sa.UUID , sa.ForeignKey('users.id') , nullable=False) ,
        sa.Column('token' , sa.String() , nullable=False) ,
        sa.Column('expires_at' , sa.DateTime() , nullable=False) ,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
