"""Add uploaded_at to Tab

Revision ID: 9ee13a6cae30
Revises: c2a8fbd4e019
Create Date: 2025-10-13 21:10:29.101938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ee13a6cae30'
down_revision: Union[str, Sequence[str], None] = 'c2a8fbd4e019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tab' , 'uploaded_at')
   # ### end Alembic commands ###
