"""Add genre to Tab

Revision ID: c2a8fbd4e019
Revises: ab56ec1587e7
Create Date: 2025-10-13 18:07:23.795045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a8fbd4e019'
down_revision: Union[str, Sequence[str], None] = 'ab56ec1587e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabs', sa.Column('genre', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabs', 'genre')
    # ### end Alembic commands ###
